### ISSUE TITLE
review

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/runner-sync-api#14]
1) název package beru jako dočasnej
https://github.com/keboola/runner-sync-api/blob/6226a6fd67d038b9f37d17e5969bd6c9152abb5a/composer.json#L18

2) konstanta controlleru?
https://github.com/keboola/runner-sync-api/blob/0afd5bca3898d218518f8c976206cfb490ccbd48/src/Controller/ActionController.php#L160-L168

3) privátní metody controlleru - nešly by zase ty, co nemaj moc závislosti přímo na controlleru vyházet ven a otestovat? `getConfigData`, `createResponse` (potomek `JsonResponse`), další mi na první pohled přijdou provázanější s controllerem/dic. 

4) kde najdu logy? dostal jsem 500 a nemůžu najít o co jde, na stdout v `docker-compose run` mi to nic nevypsalo. pamatuju si, že jsem se k tomu nějak dostal nebo to rovnou někde viděl, ale nemůžu si vzpomenout

5) ECS task má konstantní jméno - v jednom regionu asi nepůjde mít víc testovacích stacků

https://github.com/keboola/runner-sync-api/blob/e90561d4abf8d90d398d27ad5761ba4cc2d1ed38/test-cf-stack.json#L358

6) spíš dotaz - tohle projde linterem? a nešlo by to nastavit na `/var/cache/` nebo někam úplně mimo mountnutej folder pro lokální vývoj? 

https://github.com/keboola/runner-sync-api/blob/2131e4ea98c943a98ddcca1237a52b523cbbf0cf/src/Kernel.php#L20

ref https://github.com/keboola/runner-sync-api/pull/18/files#r221919703

**Comment by ondrejhlavacek** [comment]
ad 4) 

neviděl jsem je tam, ale byla to 500 s tím špatně odchycením invalid tokenem

![image](https://user-images.githubusercontent.com/497675/46290317-c91c4800-c58b-11e8-8ef0-5a6acaeb4888.png)

jinak by to mělo logy házet jen na 500? jde to nějak nasimulovat?

**Comment by odinuv** [comment]
to je divny, melo by to hazet logy na vsechny exceptions, kod na to nema vliv

**Comment by ondrejhlavacek** [comment]
eh, myslel jsem 40x, fskutečnosti to byla 401 - invalid token a ta 500 byla taky invalid token (než jsi to fixnul)

**Comment by odinuv** [comment]
ok, jeste to znovu vyzkousim jak budu u komplu, melo by to poslat na vystup

**Comment by ondrejhlavacek** [comment]
ne, tak ani na 400 mi to neháže

```
curl -X "POST" "http://localhost:82/keboola.docker-demo-sync/action/decrypt" \
     -H 'X-StorageApi-Token: ***' \
     -H 'Content-Type: text/plain; charset=utf-8' \
     -d $'{
"configData": {
	"parameters": {}
}
}'
```

```
HTTP/1.1 400 Bad Request
Date: Mon, 01 Oct 2018 13:57:54 GMT
Server: Apache/2.4.25 (Debian)
X-Powered-By: PHP/7.2.10
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Access-Control-Allow-Headers: *
Cache-Control: must-revalidate, no-cache, no-store, private
Content-Length: 103
Connection: close
Content-Type: application/json

{"error":"failed","code":0,"exceptionId":"exception-9f49790ddeb0bd45bc2412c445a28eed","status":"error"}
```

![image](https://user-images.githubusercontent.com/497675/46293161-f7515600-c592-11e8-8760-3a000f83a1db.png)

**Comment by ondrejhlavacek** [comment]
přidal jsem bod 5

**Comment by ondrejhlavacek** [comment]
pokusil jsem se to rozběhnout v ECS
```
2018-10-01 17:11:26
Getting parameters from SSM namespace "/keboola/najlos-runner-sync-api/runner-sync-api/".
2018-10-01 17:11:27
Access denied to namespace "/keboola/najlos-runner-sync-api/runner-sync-api/".
```

Lokálně přitom
```
Getting parameters from SSM namespace "/keboola/najlos-runner-sync-api/runner-sync-api/".
```

**Comment by Halama** [comment]
na jakym clusteru to spouštíš?

**Comment by ondrejhlavacek** [comment]
bude to tímhle - https://github.com/keboola/runner-sync-api/issues/9#issuecomment-425907519
vytvořil jsem si wizardem novej cluster, celý to mám nasetupovaný ve Frankfurtu, kde ten Odinovo zmiňovanej cluster není

**Comment by Halama** [comment]
jo tak to nemá vůbec roli. Ještě to není na provoz v ECS ready, pojede to pak přes roli tasku.
Odin to zatín nahackoval do role EC2 instance docker sandobxu na testingu.

**Comment by Halama** [comment]
viz. 

> (ja to poustim na instanci docker sandbox testing, ktera ma potrebny prava),

**Comment by odinuv** [comment]
@ondrejhlavacek co ti hodi `docker logs` ?

**Comment by ondrejhlavacek** [comment]
```
➜  ~ docker logs 0fcd599c8f17
> aws-parameter-filler .env /keboola/$KEBOOLA_STACK/runner-sync-api/ $KEBOOLA_STACK_REGION
Getting parameters from SSM namespace "/keboola/najlos-runner-sync-api/runner-sync-api/".
Got parameter "cpu_count".
Got parameter "kms_key_id".
Got parameter "legacy_encryption_key".
Got parameter "legacy_oauth_api_url".
Got parameter "logs_s3_bucket".
Got parameter "region".
Got parameter "storage_api_url".
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.23.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.23.0.2. Set the 'ServerName' directive globally to suppress this message
[Tue Oct 02 06:47:45.522123 2018] [mpm_prefork:notice] [pid 14] AH00163: Apache/2.4.25 (Debian) PHP/7.2.10 configured -- resuming normal operations
[Tue Oct 02 06:47:45.522720 2018] [core:notice] [pid 14] AH00094: Command line: 'apache2 -D FOREGROUND'
172.23.0.1 - - [02/Oct/2018:06:48:03 +0000] "POST /keboola.docker-demo-sync/action/decrypt HTTP/1.1" 400 457 "-" "Paw/3.1.7 (Macintosh; OS X/10.14.0) GCDHTTPRequest"
```

**Comment by odinuv** [comment]
a kdyz se podivas do bucketu, ktery mas nastaveny v `.env` v `logs_s3_bucket` ?

**Comment by odinuv** [comment]
zkus `docker-compose up test-server-local` to vypisuje trosku jinak
ale to vypada na nejakej problem s linkem na stderr

**Comment by ondrejhlavacek** [comment]
totéž

![image](https://user-images.githubusercontent.com/497675/46334831-d1c15c80-c625-11e8-9ddf-127ae38443cb.png)

**Comment by odinuv** [comment]
a tu 400 delas jakym requestem?

**Comment by ondrejhlavacek** [comment]
furt tenhle - https://github.com/keboola/runner-sync-api/issues/14#issuecomment-425918519

**Comment by odinuv** [comment]
hm, ne, to ti tam vubec nechodi zpravy z phpka, na tenhle request toho tam je kupa
![image](https://user-images.githubusercontent.com/4319320/46335458-d424b600-c627-11e8-9c88-01b577eff1d1.png)

**Comment by ondrejhlavacek** [comment]
ok, zkusím to nějak vystopovat.

S3Uploader mi hlásí

```
Error executing "PutObject" on "https://najlos-runner-sync-api-syncrunnerlogsbucket-1pggxf3quyddm.s3.eu-central-1.amazonaws.com/debug-files/2018/10/02/07/2018-10-02-07-47-33-5bb322950cd58-log.html"; 
AWS HTTP error: Client error: 
`PUT https://najlos-runner-sync-api-syncrunnerlogsbucket-1pggxf3quyddm.s3.eu-central-1.amazonaws.com/debug-files/2018/10/02/07/2018-10-02-07-47-33-5bb322950cd58-log.html` 
resulted in a `403 Forbidden` response:

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>6A77645D1D93D71F</RequestId><HostId>gj5YLGmOPL6q2nwMepITxOpiv68fZQEFJzN6vwszBJQCOCQNuZn3zEqVLVlDplwiqDDmjmShMfY=</HostId></Error>
```

skrz `LogProcessor` všechny zprávy projdou, ale nezobrazí se mi

**Comment by odinuv** [comment]
jo to je asi v poradku, vsiml jsem si ze v ty CF template je chyba u S3 opravneni
ale bez ohledu na to jestli se to uploadne nebo ne, tak to musi vyjet na vystup, to je stejne dulezitejsi

**Comment by odinuv** [comment]
no tady https://github.com/keboola/runner-sync-api/blob/master/config/packages/prod/monolog.yaml se to posila na stderr, tam uz neni moc moznosti, kde by se to mohlo pokazit

**Comment by odinuv** [comment]
cf fixed https://github.com/keboola/runner-sync-api/pull/18/commits/14fee7f11b98d0dad2994563f14556b6378409da

**Comment by ondrejhlavacek** [comment]
Když v `LogProcessor` před return

https://github.com/keboola/api-error-control/blob/22b8673cc35110a07f6106ad778c5174c9903a4e/src/Monolog/LogProcessor.php#L84

 ručně nabastlím

```
        $stderr = fopen('php://stderr', 'w');
        fwrite($stderr, $newRecord["message"] . "\n");
```
tak to vypisuje

![image](https://user-images.githubusercontent.com/497675/46336212-747bda00-c62a-11e8-892e-75381ff2df47.png)

musím se přesunout, pak to zkusím nějak dál rozlousknout

**Comment by odinuv** [comment]
no pak uz je jen JSON formatter, muzes zkusit tady 
https://github.com/keboola/runner-sync-api/blob/master/config/packages/prod/monolog.yaml
nacpat aby to misto na stderr psalo do souboru, pokud to bude fungovat, tak 
by to mozna mohlo souviset s timhle https://github.com/keboola/runner-sync-api/blob/master/Dockerfile#L62

**Comment by Halama** [comment]
https://github.com/keboola/runner-sync-api/blob/master/Dockerfile#L62 k čemu to tam je? nic takové by nemělo být potřeba

**Comment by Halama** [comment]
Shválně jsem si to zkusil a jede to ok. Jediný co jsem vyhodil je mount /tmp
![image](https://user-images.githubusercontent.com/903531/46338552-bf98eb80-c630-11e8-9ef0-bde9ec83729b.png)

**Comment by Halama** [comment]
ale ten link na ty stderr a stdout je tam imho zbytečně navíc

**Comment by odinuv** [comment]
supr, zkusim to oddelat a overim to

**Comment by Halama** [comment]
jo a spouštěl jsem `test-server` protože `web-server` nemá v docker-compose KEBOOLA_STACK a KEBOOLA_STACK_REGION

**Comment by Halama** [comment]
a na masteru teda

**Comment by odinuv** [comment]
jo, ta servica `web-server` je tam ve finale vlastne nanic

**Comment by ondrejhlavacek** [comment]
tak `test-server` mi taky valí

**Comment by ondrejhlavacek** [comment]
@Halama můžeš zkusit `test-server-local`?

**Comment by Halama** [comment]
zkusím, vypadá to že se liší jenom mountem /code že?

**Comment by Halama** [comment]
Jede, jenom jsem zas vyhodil ten mount /tmp který mi stejně přijde divný.
![image](https://user-images.githubusercontent.com/903531/46339406-ff60d280-c632-11e8-9e55-ba12d33e108e.png)

**Comment by Halama** [comment]
Ten /tmp bych udělal takhle. I když pro dev asi nemusí být vůbec jako mount ne?
```
  test-server-local:
    build:
      context: .
      dockerfile: Dockerfile-tests
    tty: true
    stdin_open: true
    ports:
      - "82:80"
    volumes:
      - tmp:/tmp
      - .:/code/
      - /var/run/docker.sock:/var/run/docker.sock
      - ./build/logs:/code/build/logs/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - KBC_TEST_TOKEN
      - KBC_TEST_URL
      - KEBOOLA_STACK
      - KEBOOLA_STACK_REGION

volumes:
  tmp:
```

**Comment by odinuv** [comment]
jop, lisi se to jen tim mountem /code/ 
coz mi pripomina, ze jsem tam chtel dat verzi 3 a referenci

**Comment by odinuv** [comment]
no ten volume prave najlosovi nefunguje https://github.com/keboola/runner-sync-api/issues/9

**Comment by ondrejhlavacek** [comment]
💩 tak mam něco divně u sebe, zkusím to celý znovu naklonovat.

**Comment by Halama** [comment]
a když by se to nemountovalo vůbec? pro sync akce je to zbytečný ne?

**Comment by ondrejhlavacek** [comment]
@Halama ještě pro info, verze Mac OS a docker?
`10.14 (18A391)`
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by Halama** [comment]
macOS 10.13.6 (17G65)
Docker
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
```

**Comment by ondrejhlavacek** [comment]
tvl, tak to jdu udělat celý načisto, fakt už nevím :-(

**Comment by ondrejhlavacek** [comment]
tak jo, restart dockeru, vymazání všech cache a čistej install zabral. kurvadrát, pardon, za takovejhle zámrd. 

![image](https://user-images.githubusercontent.com/497675/46341481-79e02100-c638-11e8-9c1d-88cfad05182e.png)

**Comment by ondrejhlavacek** [comment]
(samotnej restart dockeru nepomohl, naklonoval jsem pak znovu repo a před `composer install` jsem ještě pro sichr hodil `clear-cache`)

**Comment by ondrejhlavacek** [comment]
tak jsem to konečně doklikal a :+1: je to super!

**Comment by ondrejhlavacek** [comment]
přidal jsem 6

**Comment by odinuv** [comment]
5. fixed
6. neprojde to linterem, je to ignorovany https://github.com/keboola/runner-sync-api/blob/master/composer.json#L92 je to generovany symfony a radsi to necham jak to je
/var/cache bych nechal byt, dat to do volume neni lepsi https://github.com/keboola/runner-sync-api/pull/18#discussion_r221970182

**Comment by ondrejhlavacek** [comment]
6. ok, tak bych asi jen do readme dopsal, že se má furt mazat cache (minimálně já na to už zejtra zapomenu)

**Comment by odinuv** [comment]
6. fixed in https://github.com/keboola/runner-sync-api/commit/38bd870b0ecc9501dca81949b2c7e1b55f85b3f5
