### ISSUE TITLE
Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated

### ISSUE THREAD

**Issue by Halama** [keboola/runner-sync-api#28]
![image](https://user-images.githubusercontent.com/903531/52845148-a8055f80-3106-11e9-9d35-f9f667f58ca0.png)

> Feb 15 09:44:41 kacurez-syrup-runner-sync-api api:  {
> message: User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell.
> level: 200
> app: runner-sync-api
> pid: 26
> priority: INFO
> context: {
> }
> extra: {
> }
> component: keboola.dev-docker-demo-sync
> runId: 483729019
> http: {
> url: http://kacurez-runner-sync-api.keboola-testing.com/keboola.dev-docker-demo-sync/action/dump
> ip: 10.0.51.227
> userAgent: curl/7.54.0
> }
> token: {
> id: 151450
> description: sync actions test
> }
> owner: {
> id: 4088
> name: Martin's Sandbox
> }
> }

**Comment by Halama** [comment]
Vypadá to že to nic nerozbíjí ale zbytečně to flooduje log.

**Comment by Halama** [comment]
Sype to tech deprecated věcí víc koukám:
```
User Deprecated: A tree builder without a root node is deprecated si..
```

**Comment by odinuv** [comment]
hm, to loguje jako info? to je divny
jsou jen dve moznosti - downgradnout symfony nebo to nejak ignoroat v logu

**Comment by Halama** [comment]
Tak treba je nejak spatne nastaveny to logovani?
A moznost to pofixovat to neni?

**Comment by Halama** [comment]
V nejhorsim to teda muzeme odignorovat ve filtru Papertrailu.

**Comment by odinuv** [comment]
mozna je to nejak blbe v logovani, prislo mi, ze lokalne mi to nepsalo
pofixovat to nejde, musi to byt zpetne kompatibilni se symfony 2

**Comment by odinuv** [comment]
podivam se na to
