### ISSUE TITLE
Apache logs

### ISSUE THREAD

**Issue by odinuv** [keboola/runner-sync-api#5]
this is probably not needed https://github.com/keboola/runner-sync-api/blob/master/docker/sync-api.conf#L22

**Comment by Halama** [comment]
to bych vyhodil a nechal to at to loguje na stdout a stdeerr jak to má nastavené v defaultu.
```
lrwxrwxrwx 1 root     root       11 Mar 14 15:16 access.log -> /dev/stdout
lrwxrwxrwx 1 root     root       11 Mar 14 15:16 error.log -> /dev/stderr
lrwxrwxrwx 1 root     root       11 Mar 14 15:16 other_vhosts_access.log -> /dev/stdout
```
Jenom bych přidal logování runId https://github.com/keboola/connection/blob/master/docker/php-apache/logging.conf
