### ISSUE TITLE
document list api call

### ISSUE THREAD

**Issue by odinuv** [keboola/runner-sync-api#6]
or remove it?

**Comment by Halama** [comment]
co to je?

**Comment by odinuv** [comment]
vylistuje akce komponenty http://54.84.177.162:8080/keboola.docker-demo-sync/list
je to prijemny z pohledu api, ale jinak v podstate zbytecny, udelal jsem si to tam na testovani

**Comment by ondrejhlavacek** [comment]
přesunul bych sem celý apib synchronních akcí

**Comment by odinuv** [comment]
no vsak to je jeden api call https://kebooladocker.docs.apiary.io/#reference/actions/run-custom-component-action/process-action
otazka jestli mit jeste ten list

a kdyz uz jsme u toho tak je otazka jestli sem pridat i encrypt, nebo to dat jeste do dalsi appky (coz bych udelal spis)

**Comment by odinuv** [comment]
wip appky na encrypt https://github.com/keboola/encryption-api/pull/1

**Comment by odinuv** [comment]
fixed in 252c63f7201c4ba56a03f8e769a41bfc8ebb7b97
